services:

  # =================================
  # CORE SERVICES
  # =================================

  eureka-server:
    build:
      context: ./EurekaServerApp
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    env_file:
      - .env
    networks:
      - my-biz-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/eureka/apps"]
      interval: 10s
      timeout: 5s
      retries: 5

  api-gateway:
    build:
      context: ./API-Gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - my-biz-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  config-server:
    build:
      context: ./ConfigServerApp
      dockerfile: Dockerfile
    container_name: config-server
    ports:
      - "8888:8888"
    env_file:
      - .env
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - my-biz-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

#=======================================================
#MICROSERVICES
#=======================================================
  product-service:
    build:
      context: ./ProductServiceApp
      dockerfile: Dockerfile
    container_name: product-service
    ports:
      - "8094:8094"
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
      mysql-product:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - my-biz-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8094/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5


  urlshortener-service:
    build:
      context: ./URLShortener
      dockerfile: Dockerfile
    container_name: urlshortener-service
    ports:
      - "8079:8079"
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
      mysql-url-shortener:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - my-biz-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8079/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5








  order-service:
    build:
      context: ./OrderServiceApp
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "8090:8090"
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
      mysql-order:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - my-biz-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5






  user-service:
    build:
      context: ./UserManagementAPI
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8092:8092"
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
      mysql-user:
        condition: service_healthy
    env_file:
      - .env
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - my-biz-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8092/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5


  otp-service:
    build:
      context: ./OTPSystem
      dockerfile: Dockerfile
    container_name: otp-service
    ports:
      - "8096:8096"
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
      mysql-otp:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - my-biz-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8096/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5


  notification-service:
    build:
      context: ./NotificationSystem
      dockerfile: Dockerfile
    container_name: notification-service
    ports:
      - "8098:8098"
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
      mysql-notification:
        condition: service_healthy
    env_file:
      - .env
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - my-biz-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8098/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5


  payment-service:
    build:
      context: ./PaymentServiceApp
      dockerfile: Dockerfile
    container_name: payment-service
    ports:
      - "8100:8100"
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
      mysql-payment:
        condition: service_healthy
    env_file:
      - .env
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - my-biz-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8100/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5


  open-ai:
    build:
      context: ./OpenAI
      dockerfile: Dockerfile
    container_name: open-ai
    ports:
      - "8102:8102"
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
      psql-openai:
        condition: service_healthy
    env_file:
      - .env
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - my-biz-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8102/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5









#=====================================================
# DATABASES
#=====================================================
  mysql-product:
    image: mysql:8
    container_name: mysql-product
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${PRODUCT_DB}
    ports:
      - "3308:3306"
    networks:
      - my-biz-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${DATABASE_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10


  mysql-user:
    image: mysql:8
    container_name: mysql-user
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${USER_MANAGEMENT_DB}
    ports:
      - "3309:3306"
    networks:
      - my-biz-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${DATABASE_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10


  mysql-otp:
    image: mysql:8
    container_name: mysql-otp
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${OTP_DB}
    ports:
      - "3310:3306"
    networks:
      - my-biz-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${DATABASE_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10


  mysql-order:
    image: mysql:8
    container_name: mysql-order
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${ORDER_DB}
    ports:
      - "3311:3306"
    networks:
      - my-biz-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${DATABASE_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10


  mysql-notification:
    image: mysql:8
    container_name: mysql-notification
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${NOTIFICATIONS_DB}
    ports:
      - "3312:3306"
    networks:
      - my-biz-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${DATABASE_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10


  mysql-payment:
    image: mysql:8
    container_name: mysql-payment
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${PAYMENTDB}
    ports:
      - "3313:3306"
    networks:
      - my-biz-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${DATABASE_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10

  mysql-url-shortener:
    image: mysql:8
    container_name: mysql-url-shortener
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${URL_SHORTENER_DB}
    ports:
      - "3314:3306"
    networks:
      - my-biz-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${DATABASE_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10


  psql-openai:
    image: pgvector/pgvector:pg18
    container_name: psql-openai
    environment:    
      POSTGRES_DB: ${VECTORDB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - my-biz-network
    restart: unless-stopped
    healthcheck:   
      test: ["CMD-SHELL", "pg_isready -U postgres -d ${VECTORDB}"]
      interval: 10s
      timeout: 5s
      retries: 10





#====================================================
#Monitoring & Loggigng
#====================================================
  
  redis:
    image: redis:7.4-alpine
    container_name: redis
    command: redis-server --requirepass master
    networks:
      - my-biz-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "master", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10



  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    networks:
      - my-biz-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", curl", "-f", "http://localhost:11434/api/tags"]
      interval: 5s
      timeout: 5s
      retries: 10

      
#====================================================
#MESSAGING
#====================================================
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - my-biz-network
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    container_name: kafka
    hostname: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - my-biz-network
    restart: unless-stopped

  



# =================================
# NETWORKS
# =================================

networks:
  my-biz-network:
    driver: bridge