apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config

data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:

      - job_name: 'product-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets:
              - product-service:8094

      - job_name: 'otp-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets:
              - otp-service:8096