spring.application.name=API-Gateway
#Port for the API Gateway to listen on
server.port=8080
#Eureka client configuration for service discovery
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

#Redis configuration for session management
spring.cache.type=redis
spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.password=master

#Rate limiting configuration
ratelimit.timeframe=60
ratelimiter.burstcapacity=20

#Microservice routes configuration
spring.cloud.gateway.routes[0].id=usermanagementapi
spring.cloud.gateway.routes[0].uri=lb://UserManagementAPI
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/users/**
spring.cloud.gateway.routes[0].filters[0].name=RequestRateLimiter
spring.cloud.gateway.routes[0].filters[0].args.key-resolver=#{@userKeyResolver}
spring.cloud.gateway.routes[0].filters[0].args.redis-rate-limiter.replenishRate=5
spring.cloud.gateway.routes[0].filters[0].args.redis-rate-limiter.burstCapacity=10

spring.cloud.gateway.routes[8].id=usermanagementapi
spring.cloud.gateway.routes[8].uri=lb://UserManagementAPI
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/auth/**


spring.cloud.gateway.routes[1].id=product-service
spring.cloud.gateway.routes[1].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/products/**

spring.cloud.gateway.routes[2].id=order-service
spring.cloud.gateway.routes[2].uri=lb://ORDER-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/orders/**
spring.cloud.gateway.routes[2].filters[0].name=RequestRateLimiter
spring.cloud.gateway.routes[2].filters[0].args.key-resolver=#{@userKeyResolver}
spring.cloud.gateway.routes[2].filters[0].args.redis-rate-limiter.replenishRate=5
spring.cloud.gateway.routes[2].filters[0].args.redis-rate-limiter.burstCapacity=10

spring.cloud.gateway.routes[3].id=paymentserviceapp
spring.cloud.gateway.routes[3].uri=lb://PaymentServiceApp
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/payments/**
spring.cloud.gateway.routes[3].filters[0].name=RequestRateLimiter
spring.cloud.gateway.routes[3].filters[0].args.key-resolver=#{@userKeyResolver}
spring.cloud.gateway.routes[3].filters[0].args.redis-rate-limiter.replenishRate=5
spring.cloud.gateway.routes[3].filters[0].args.redis-rate-limiter.burstCapacity=10

spring.cloud.gateway.routes[4].id=otp-service
spring.cloud.gateway.routes[4].uri=lb://OTP-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/otp/**

spring.cloud.gateway.routes[5].id=notification-service
spring.cloud.gateway.routes[5].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/notifications/**
spring.cloud.gateway.routes[5].filters[0].name=RequestRateLimiter
spring.cloud.gateway.routes[5].filters[0].args.key-resolver=#{@userKeyResolver}
spring.cloud.gateway.routes[5].filters[0].args.redis-rate-limiter.replenishRate=5
spring.cloud.gateway.routes[5].filters[0].args.redis-rate-limiter.burstCapacity=10

spring.cloud.gateway.routes[6].id=urlshortener
spring.cloud.gateway.routes[6].uri=lb://URLShortener
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/shortener/**


spring.cloud.gateway.routes[7].id=openai
spring.cloud.gateway.routes[7].uri=lb://OPENAI
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/ai/**


#Logging configuration
logging.level.org.springframework.cloud.gateway=INFO
logging.level.reactor.netty=DEBUG

#Actuator configuration for monitoring and health checks
management.endpoints.web.exposure.include=health, metrics, prometheus
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always

#Prometheus configuration for monitoring
management.metrics.export.prometheus.enabled=true
