spring.application.name=ConfigServerApp
server.port=8888
#Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

#Spring Cloud Config Server Configuration
spring.cloud.config.server.git.uri=http://github.com//harshardhan/branchpickingsystem.git
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.default-label=main
