spring.application.name=openai


server.port=8102

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=llama3

spring.ai.ollama.connection-timeout=5s
spring.ai.ollama.read-timeout=60s

#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#eureka.instance.prefer-ip-address=true
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
#eureka.instance.hostname=localhost
#server.address=127.0.0.1
#spring.cloud.client.hostname=localhost
#spring.cloud.client.ip-address=127.0.0.1

#eureka.instance.ip-address=127.0.0.1
