spring.application.name=openai

server.port=8102

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=phi3
spring.ai.ollama.chat.options.temperature=0.2
server.tomcat.connection-timeout=120s
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

